version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  web:
    image: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    restart: always
